#!/usr/bin/env python3
"""
Builds scripts/og-fonts.css: the card's two webfonts, base64 inside the file.

The card used to pull them off Google Fonts at render time, and headless Chrome
photographed the page before they landed — with `display: block` that produced a
card with no words on it. Embedding removes the race and the network both. It
also pins the faces, so a card rendered next year matches the one rendered
today.

    python3 scripts/fetch-og-fonts.py     # only needed if the faces change

Latin subsets only. The card is English and each extra subset is another 20 KB.
"""

import base64
import re
import subprocess
from pathlib import Path

API = (
    "https://fonts.googleapis.com/css2"
    "?family=Newsreader:opsz,wght@6..72,400"
    "&family=Geist:wght@400;500;600"
    "&display=swap"
)
# Google serves woff2 only to a browser it recognises; curl's own agent gets ttf.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)

OUT = Path(__file__).resolve().parent / "og-fonts.css"


def get(url: str) -> bytes:
    return subprocess.run(
        ["curl", "-sSfL", "-A", UA, url], check=True, capture_output=True
    ).stdout


css = get(API).decode()

# Each @font-face is preceded by a comment naming its subset. Keep latin.
blocks = re.split(r"(?=/\* [a-z0-9-]+ \*/)", css)
kept = [b for b in blocks if b.startswith("/* latin */")]
if not kept:
    raise SystemExit("No latin subsets in the response. Did the API change?")

out = []
for block in kept:
    url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
    data = base64.b64encode(get(url)).decode()
    out.append(
        re.sub(
            r"url\(https://[^)]+\.woff2\)",
            f"url(data:font/woff2;base64,{data})",
            block,
        )
    )

header = (
    "/* Generated by scripts/fetch-og-fonts.py. Do not edit: the base64 is the\n"
    "   font. Regenerate if the card's faces or weights change. */\n"
)
OUT.write_text(header + "".join(out))
print(f"wrote {OUT.name} ({OUT.stat().st_size // 1024} KB, {len(kept)} faces)")
