/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as AuthedProposalsIdRouteImport } from './routes/_authed.proposals.$id'
import { Route as AuthedProposalsNewRouteImport } from './routes/_authed.proposals.new'
import { Route as ApiTrackVisitIdRouteImport } from './routes/api/track.$visitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProposalsIdRoute = AuthedProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProposalsNewRoute = AuthedProposalsNewRouteImport.update({
  id: '/proposals/new',
  path: '/proposals/new',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiTrackVisitIdRoute = ApiTrackVisitIdRouteImport.update({
  id: '/api/track/$visitId',
  path: '/api/track/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$token': typeof PTokenRoute
  '/proposals/$id': typeof AuthedProposalsIdRoute
  '/proposals/new': typeof AuthedProposalsNewRoute
  '/api/track/$visitId': typeof ApiTrackVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$token': typeof PTokenRoute
  '/proposals/$id': typeof AuthedProposalsIdRoute
  '/proposals/new': typeof AuthedProposalsNewRoute
  '/api/track/$visitId': typeof ApiTrackVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$token': typeof PTokenRoute
  '/_authed/proposals/$id': typeof AuthedProposalsIdRoute
  '/_authed/proposals/new': typeof AuthedProposalsNewRoute
  '/api/track/$visitId': typeof ApiTrackVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/auth/callback'
    | '/p/$token'
    | '/proposals/$id'
    | '/proposals/new'
    | '/api/track/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/auth/callback'
    | '/p/$token'
    | '/proposals/$id'
    | '/proposals/new'
    | '/api/track/$visitId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/auth/callback'
    | '/p/$token'
    | '/_authed/proposals/$id'
    | '/_authed/proposals/new'
    | '/api/track/$visitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PTokenRoute: typeof PTokenRoute
  ApiTrackVisitIdRoute: typeof ApiTrackVisitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/proposals/$id': {
      id: '/_authed/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof AuthedProposalsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/proposals/new': {
      id: '/_authed/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof AuthedProposalsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/track/$visitId': {
      id: '/api/track/$visitId'
      path: '/api/track/$visitId'
      fullPath: '/api/track/$visitId'
      preLoaderRoute: typeof ApiTrackVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProposalsIdRoute: typeof AuthedProposalsIdRoute
  AuthedProposalsNewRoute: typeof AuthedProposalsNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProposalsIdRoute: AuthedProposalsIdRoute,
  AuthedProposalsNewRoute: AuthedProposalsNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PTokenRoute: PTokenRoute,
  ApiTrackVisitIdRoute: ApiTrackVisitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
