/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as RSourceRouteImport } from './routes/r.$source'
import { Route as AuthedProposalsIdRouteImport } from './routes/_authed.proposals.$id'
import { Route as AuthedProposalsNewRouteImport } from './routes/_authed.proposals.new'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe.webhook'
import { Route as ApiTrackVisitIdRouteImport } from './routes/api/track.$visitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RSourceRoute = RSourceRouteImport.update({
  id: '/r/$source',
  path: '/r/$source',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProposalsIdRoute = AuthedProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProposalsNewRoute = AuthedProposalsNewRouteImport.update({
  id: '/proposals/new',
  path: '/proposals/new',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackVisitIdRoute = ApiTrackVisitIdRouteImport.update({
  id: '/api/track/$visitId',
  path: '/api/track/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/dpa': typeof DpaRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$token': typeof PTokenRoute
  '/r/$source': typeof RSourceRoute
  '/proposals/$id': typeof AuthedProposalsIdRoute
  '/proposals/new': typeof AuthedProposalsNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/track/$visitId': typeof ApiTrackVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/dpa': typeof DpaRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$token': typeof PTokenRoute
  '/r/$source': typeof RSourceRoute
  '/proposals/$id': typeof AuthedProposalsIdRoute
  '/proposals/new': typeof AuthedProposalsNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/track/$visitId': typeof ApiTrackVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/demo': typeof DemoRoute
  '/dpa': typeof DpaRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$token': typeof PTokenRoute
  '/r/$source': typeof RSourceRoute
  '/_authed/proposals/$id': typeof AuthedProposalsIdRoute
  '/_authed/proposals/new': typeof AuthedProposalsNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/track/$visitId': typeof ApiTrackVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/dpa'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard'
    | '/settings'
    | '/auth/callback'
    | '/p/$token'
    | '/r/$source'
    | '/proposals/$id'
    | '/proposals/new'
    | '/api/stripe/webhook'
    | '/api/track/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/dpa'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard'
    | '/settings'
    | '/auth/callback'
    | '/p/$token'
    | '/r/$source'
    | '/proposals/$id'
    | '/proposals/new'
    | '/api/stripe/webhook'
    | '/api/track/$visitId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/demo'
    | '/dpa'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/_authed/dashboard'
    | '/_authed/settings'
    | '/auth/callback'
    | '/p/$token'
    | '/r/$source'
    | '/_authed/proposals/$id'
    | '/_authed/proposals/new'
    | '/api/stripe/webhook'
    | '/api/track/$visitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  DemoRoute: typeof DemoRoute
  DpaRoute: typeof DpaRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PTokenRoute: typeof PTokenRoute
  RSourceRoute: typeof RSourceRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiTrackVisitIdRoute: typeof ApiTrackVisitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$source': {
      id: '/r/$source'
      path: '/r/$source'
      fullPath: '/r/$source'
      preLoaderRoute: typeof RSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/proposals/$id': {
      id: '/_authed/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof AuthedProposalsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/proposals/new': {
      id: '/_authed/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof AuthedProposalsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track/$visitId': {
      id: '/api/track/$visitId'
      path: '/api/track/$visitId'
      fullPath: '/api/track/$visitId'
      preLoaderRoute: typeof ApiTrackVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedProposalsIdRoute: typeof AuthedProposalsIdRoute
  AuthedProposalsNewRoute: typeof AuthedProposalsNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedProposalsIdRoute: AuthedProposalsIdRoute,
  AuthedProposalsNewRoute: AuthedProposalsNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DemoRoute: DemoRoute,
  DpaRoute: DpaRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PTokenRoute: PTokenRoute,
  RSourceRoute: RSourceRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiTrackVisitIdRoute: ApiTrackVisitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
