/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProposalTrackingRouteImport } from './routes/proposal-tracking'
import { Route as ProposalTrackingForAgenciesRouteImport } from './routes/proposal-tracking-for-agencies'
import { Route as ProposalTrackingForFractionalExecutivesRouteImport } from './routes/proposal-tracking-for-fractional-executives'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedWelcomeRouteImport } from './routes/_authed.welcome'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as RSourceRouteImport } from './routes/r.$source'
import { Route as VsDocsendRouteImport } from './routes/vs.docsend'
import { Route as VsPandadocRouteImport } from './routes/vs.pandadoc'
import { Route as VsProposifyRouteImport } from './routes/vs.proposify'
import { Route as AuthedProposalsIdRouteImport } from './routes/_authed.proposals.$id'
import { Route as AuthedProposalsNewRouteImport } from './routes/_authed.proposals.new'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe.webhook'
import { Route as ApiTrackVisitIdRouteImport } from './routes/api/track.$visitId'
import { Route as PSlugTokenRouteImport } from './routes/p.$slug.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalTrackingRoute = ProposalTrackingRouteImport.update({
  id: '/proposal-tracking',
  path: '/proposal-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalTrackingForAgenciesRoute =
  ProposalTrackingForAgenciesRouteImport.update({
    id: '/proposal-tracking-for-agencies',
    path: '/proposal-tracking-for-agencies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProposalTrackingForFractionalExecutivesRoute =
  ProposalTrackingForFractionalExecutivesRouteImport.update({
    id: '/proposal-tracking-for-fractional-executives',
    path: '/proposal-tracking-for-fractional-executives',
    getParentRoute: () => rootRouteImport,
  } as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWelcomeRoute = AuthedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RSourceRoute = RSourceRouteImport.update({
  id: '/r/$source',
  path: '/r/$source',
  getParentRoute: () => rootRouteImport,
} as any)
const VsDocsendRoute = VsDocsendRouteImport.update({
  id: '/vs/docsend',
  path: '/vs/docsend',
  getParentRoute: () => rootRouteImport,
} as any)
const VsPandadocRoute = VsPandadocRouteImport.update({
  id: '/vs/pandadoc',
  path: '/vs/pandadoc',
  getParentRoute: () => rootRouteImport,
} as any)
const VsProposifyRoute = VsProposifyRouteImport.update({
  id: '/vs/proposify',
  path: '/vs/proposify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProposalsIdRoute = AuthedProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProposalsNewRoute = AuthedProposalsNewRouteImport.update({
  id: '/proposals/new',
  path: '/proposals/new',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackVisitIdRoute = ApiTrackVisitIdRouteImport.update({
  id: '/api/track/$visitId',
  path: '/api/track/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugTokenRoute = PSlugTokenRouteImport.update({
  id: '/p/$slug/$token',
  path: '/p/$slug/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRoute
  '/dpa': typeof DpaRoute
  '/guides': typeof GuidesRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/proposal-tracking': typeof ProposalTrackingRoute
  '/proposal-tracking-for-agencies': typeof ProposalTrackingForAgenciesRoute
  '/proposal-tracking-for-fractional-executives': typeof ProposalTrackingForFractionalExecutivesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/p/$token': typeof PTokenRoute
  '/r/$source': typeof RSourceRoute
  '/vs/docsend': typeof VsDocsendRoute
  '/vs/pandadoc': typeof VsPandadocRoute
  '/vs/proposify': typeof VsProposifyRoute
  '/guides/': typeof GuidesIndexRoute
  '/proposals/$id': typeof AuthedProposalsIdRoute
  '/proposals/new': typeof AuthedProposalsNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/track/$visitId': typeof ApiTrackVisitIdRoute
  '/p/$slug/$token': typeof PSlugTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRoute
  '/dpa': typeof DpaRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/proposal-tracking': typeof ProposalTrackingRoute
  '/proposal-tracking-for-agencies': typeof ProposalTrackingForAgenciesRoute
  '/proposal-tracking-for-fractional-executives': typeof ProposalTrackingForFractionalExecutivesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/p/$token': typeof PTokenRoute
  '/r/$source': typeof RSourceRoute
  '/vs/docsend': typeof VsDocsendRoute
  '/vs/pandadoc': typeof VsPandadocRoute
  '/vs/proposify': typeof VsProposifyRoute
  '/guides': typeof GuidesIndexRoute
  '/proposals/$id': typeof AuthedProposalsIdRoute
  '/proposals/new': typeof AuthedProposalsNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/track/$visitId': typeof ApiTrackVisitIdRoute
  '/p/$slug/$token': typeof PSlugTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/demo': typeof DemoRoute
  '/dpa': typeof DpaRoute
  '/guides': typeof GuidesRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/proposal-tracking': typeof ProposalTrackingRoute
  '/proposal-tracking-for-agencies': typeof ProposalTrackingForAgenciesRoute
  '/proposal-tracking-for-fractional-executives': typeof ProposalTrackingForFractionalExecutivesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/welcome': typeof AuthedWelcomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/p/$token': typeof PTokenRoute
  '/r/$source': typeof RSourceRoute
  '/vs/docsend': typeof VsDocsendRoute
  '/vs/pandadoc': typeof VsPandadocRoute
  '/vs/proposify': typeof VsProposifyRoute
  '/guides/': typeof GuidesIndexRoute
  '/_authed/proposals/$id': typeof AuthedProposalsIdRoute
  '/_authed/proposals/new': typeof AuthedProposalsNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/track/$visitId': typeof ApiTrackVisitIdRoute
  '/p/$slug/$token': typeof PSlugTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo'
    | '/dpa'
    | '/guides'
    | '/llms.txt'
    | '/login'
    | '/privacy'
    | '/proposal-tracking'
    | '/proposal-tracking-for-agencies'
    | '/proposal-tracking-for-fractional-executives'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard'
    | '/settings'
    | '/welcome'
    | '/auth/callback'
    | '/guides/$slug'
    | '/p/$token'
    | '/r/$source'
    | '/vs/docsend'
    | '/vs/pandadoc'
    | '/vs/proposify'
    | '/guides/'
    | '/proposals/$id'
    | '/proposals/new'
    | '/api/stripe/webhook'
    | '/api/track/$visitId'
    | '/p/$slug/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo'
    | '/dpa'
    | '/llms.txt'
    | '/login'
    | '/privacy'
    | '/proposal-tracking'
    | '/proposal-tracking-for-agencies'
    | '/proposal-tracking-for-fractional-executives'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard'
    | '/settings'
    | '/welcome'
    | '/auth/callback'
    | '/guides/$slug'
    | '/p/$token'
    | '/r/$source'
    | '/vs/docsend'
    | '/vs/pandadoc'
    | '/vs/proposify'
    | '/guides'
    | '/proposals/$id'
    | '/proposals/new'
    | '/api/stripe/webhook'
    | '/api/track/$visitId'
    | '/p/$slug/$token'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/demo'
    | '/dpa'
    | '/guides'
    | '/llms.txt'
    | '/login'
    | '/privacy'
    | '/proposal-tracking'
    | '/proposal-tracking-for-agencies'
    | '/proposal-tracking-for-fractional-executives'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/_authed/dashboard'
    | '/_authed/settings'
    | '/_authed/welcome'
    | '/auth/callback'
    | '/guides/$slug'
    | '/p/$token'
    | '/r/$source'
    | '/vs/docsend'
    | '/vs/pandadoc'
    | '/vs/proposify'
    | '/guides/'
    | '/_authed/proposals/$id'
    | '/_authed/proposals/new'
    | '/api/stripe/webhook'
    | '/api/track/$visitId'
    | '/p/$slug/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  DemoRoute: typeof DemoRoute
  DpaRoute: typeof DpaRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProposalTrackingRoute: typeof ProposalTrackingRoute
  ProposalTrackingForAgenciesRoute: typeof ProposalTrackingForAgenciesRoute
  ProposalTrackingForFractionalExecutivesRoute: typeof ProposalTrackingForFractionalExecutivesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PTokenRoute: typeof PTokenRoute
  RSourceRoute: typeof RSourceRoute
  VsDocsendRoute: typeof VsDocsendRoute
  VsPandadocRoute: typeof VsPandadocRoute
  VsProposifyRoute: typeof VsProposifyRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiTrackVisitIdRoute: typeof ApiTrackVisitIdRoute
  PSlugTokenRoute: typeof PSlugTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal-tracking': {
      id: '/proposal-tracking'
      path: '/proposal-tracking'
      fullPath: '/proposal-tracking'
      preLoaderRoute: typeof ProposalTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal-tracking-for-agencies': {
      id: '/proposal-tracking-for-agencies'
      path: '/proposal-tracking-for-agencies'
      fullPath: '/proposal-tracking-for-agencies'
      preLoaderRoute: typeof ProposalTrackingForAgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal-tracking-for-fractional-executives': {
      id: '/proposal-tracking-for-fractional-executives'
      path: '/proposal-tracking-for-fractional-executives'
      fullPath: '/proposal-tracking-for-fractional-executives'
      preLoaderRoute: typeof ProposalTrackingForFractionalExecutivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/welcome': {
      id: '/_authed/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthedWelcomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$source': {
      id: '/r/$source'
      path: '/r/$source'
      fullPath: '/r/$source'
      preLoaderRoute: typeof RSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/docsend': {
      id: '/vs/docsend'
      path: '/vs/docsend'
      fullPath: '/vs/docsend'
      preLoaderRoute: typeof VsDocsendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/pandadoc': {
      id: '/vs/pandadoc'
      path: '/vs/pandadoc'
      fullPath: '/vs/pandadoc'
      preLoaderRoute: typeof VsPandadocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/proposify': {
      id: '/vs/proposify'
      path: '/vs/proposify'
      fullPath: '/vs/proposify'
      preLoaderRoute: typeof VsProposifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/proposals/$id': {
      id: '/_authed/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof AuthedProposalsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/proposals/new': {
      id: '/_authed/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof AuthedProposalsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track/$visitId': {
      id: '/api/track/$visitId'
      path: '/api/track/$visitId'
      fullPath: '/api/track/$visitId'
      preLoaderRoute: typeof ApiTrackVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug/$token': {
      id: '/p/$slug/$token'
      path: '/p/$slug/$token'
      fullPath: '/p/$slug/$token'
      preLoaderRoute: typeof PSlugTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedWelcomeRoute: typeof AuthedWelcomeRoute
  AuthedProposalsIdRoute: typeof AuthedProposalsIdRoute
  AuthedProposalsNewRoute: typeof AuthedProposalsNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedWelcomeRoute: AuthedWelcomeRoute,
  AuthedProposalsIdRoute: AuthedProposalsIdRoute,
  AuthedProposalsNewRoute: AuthedProposalsNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  DemoRoute: DemoRoute,
  DpaRoute: DpaRoute,
  GuidesRoute: GuidesRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProposalTrackingRoute: ProposalTrackingRoute,
  ProposalTrackingForAgenciesRoute: ProposalTrackingForAgenciesRoute,
  ProposalTrackingForFractionalExecutivesRoute:
    ProposalTrackingForFractionalExecutivesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PTokenRoute: PTokenRoute,
  RSourceRoute: RSourceRoute,
  VsDocsendRoute: VsDocsendRoute,
  VsPandadocRoute: VsPandadocRoute,
  VsProposifyRoute: VsProposifyRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiTrackVisitIdRoute: ApiTrackVisitIdRoute,
  PSlugTokenRoute: PSlugTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
